
export enum AppView {
  DASHBOARD = 'DASHBOARD',
  INVENTORY_POWDER = 'INVENTORY_POWDER',
  INVENTORY_CONTAINERS = 'INVENTORY_CONTAINERS',
  INVENTORY_SOLUTIONS = 'INVENTORY_SOLUTIONS',
  BATCH_MANAGEMENT = 'BATCH_MANAGEMENT',
  BATCH_CREATION = 'BATCH_CREATION',
  BATCH_DETAILS = 'BATCH_DETAILS',
  MEDIA_LOT_DETAILS = 'MEDIA_LOT_DETAILS',
  SOLUTION_LOT_DETAILS = 'SOLUTION_LOT_DETAILS',
  CONTAINER_LOT_DETAILS = 'CONTAINER_LOT_DETAILS',
  MEDIA_PREP = 'MEDIA_PREP',
  STERILIZATION = 'STERILIZATION',
  DISPENSING = 'DISPENSING',
  FINE_TUNING = 'FINE_TUNING',
  RECONCILIATION = 'RECONCILIATION',
  QUALITY_VALIDATION = 'QUALITY_VALIDATION',
  REPORTS = 'REPORTS',
  REPORTS_STATISTICS = 'REPORTS_STATISTICS',
  AUDIT_LOG = 'AUDIT_LOG',
  PRODUCT_MASTER = 'PRODUCT_MASTER',
  CONTAINER_LOT_CREATION = 'CONTAINER_LOT_CREATION',
  POWDER_LOT_CREATION = 'POWDER_LOT_CREATION',
  SOLUTION_CREATION = 'SOLUTION_CREATION',
  RECONCILE_POWDER = 'RECONCILE_POWDER',
  RECONCILE_SOLUTIONS = 'RECONCILE_SOLUTIONS',
  RECONCILE_CONTAINERS = 'RECONCILE_CONTAINERS',
  RECONCILE_BATCHES_LIST = 'RECONCILE_BATCHES_LIST'
}

export interface KPI {
  label: string;
  value: string | number;
  unit?: string;
  status?: 'success' | 'warning' | 'error' | 'info';
  subtext?: string;
}

export interface Batch {
  id: string;
  mediaType: string;
  status: 'Draft' | 'In Preparation' | 'Sterilizing' | 'Released' | 'Rejected';
  preparedBy: string;
  dateCreated: string;
}
